name: Make Generate
on: push

jobs:
  run:
    name: Make Generate Template
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Make
      run: make

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        message: "on push: make"
        add: "hack/00-osd-managed-cluster-config*.yaml.tmpl"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
